#!/bin/zsh

# Paths and variables
export EDITOR='vim'

export ZSH="/Users/chad/.oh-my-zsh"

export dotfiles=$HOME/.dotfiles
export DOTFILES=$dotfiles
export ZSH_CUSTOM=$DOTFILES/Zsh/custom

export PATH="/usr/local/sbin:$PATH"

# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh

# nvm config
  export NVM_DIR="$HOME/.nvm"
  [ -s "/usr/local/opt/nvm/nvm.sh" ] && . "/usr/local/opt/nvm/nvm.sh"  # This loads nvm
  [ -s "/usr/local/opt/nvm/etc/bash_completion.d/nvm" ] && . "/usr/local/opt/nvm/etc/bash_completion.d/nvm"  # This loads nvm bash_completion

# Zsh Settings
plugins=(git zsh-history-substring-search)
ZSH_THEME="Agnoster"
COMPLETION_WAITING_DOTS="true"

# Load Oh-My-Zsh and powerlevel10k
source $ZSH/oh-my-zsh.sh
source ~/powerlevel10k/powerlevel10k.zsh-theme

# Load aliases and functions
typeset -U my_aliases
typeset -U my_functions
my_aliases=($DOTFILES/**/aliases.sh)
my_functions=($DOTFILES/**/functions.sh)
my_files=($my_aliases $my_functions)

for file in ${my_files}
do
	source $file
done

# Zsh Plugin initizlization
source $ZSH_CUSTOM/plugin-initexport
